### ISSUE TITLE
fix bot

### ISSUE THREAD

**Issue by ConnorMcF** [Magnitex/frontend#2]
im dumb

**Comment by xmatmen** [comment]
ok done

**Comment by ConnorMcF** [comment]
still having issue in patch

**Comment by ConnorMcF** [comment]
-rep bad devs won't acknowledge blocking issue

**Comment by xmatmen** [comment]
ill block you connor

**Comment by ConnorMcF** [comment]
-rep bad devs changing what I said initially, it was "thank"

**Comment by ConnorMcF** [comment]
-rep acknowledge issue

**Comment by ConnorMcF** [comment]
This issue needs to be fixed, it's blocking my workflow.

**Comment by ConnorMcF** [comment]
fix bot?
bot machine broke
understandable, have a nice day
